<?php
declare(strict_types=1);

namespace MageOS\AiShoppingAssistant\Model\Backend;

use Magento\Catalog\Api\Data\ProductInterface as MagentoProductInterface;
use Magento\Catalog\Pricing\Price\FinalPrice;
use Magento\Catalog\Pricing\Price\RegularPrice;
use Magento\CatalogUrlRewrite\Model\ProductUrlRewriteGenerator;
use Magento\ConfigurableProduct\Model\Product\Type\Configurable;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use MageOS\AiShoppingAssistant\Model\Agent\SessionContext;
use MageOS\AiShoppingAssistant\Model\Data\Product;

final class ProductMapper
{
    public function __construct(
        private readonly \Magento\Store\Model\StoreManagerInterface $storeManager,
        private readonly \MageOS\AiShoppingAssistant\Api\Backend\ProductImageUrlInterface $productImageUrl,
        private readonly \MageOS\AiShoppingAssistant\Model\Backend\Provider\HelperImageUrl $helperImageUrl,
        private readonly \MageOS\AiShoppingAssistant\Model\Backend\Salability $salability,
        private readonly \MageOS\AiShoppingAssistant\Api\Backend\ProductOptionsProviderInterface $optionsProvider,
        private readonly \Magento\UrlRewrite\Model\UrlFinderInterface $urlFinder
    ) {
    }

    public function toProduct(MagentoProductInterface $p, SessionContext $ctx, ?bool $inStock = null): Product
    {
        $summary = $this->optionsProvider->summarize($p);
        $prices = $this->prices($p);

        $data = [
            'product_id' => (string)$p->getId(),
            'title' => (string)$p->getName(),
            'brand' => $this->brand($p),
            'price' => $prices['price'],
            'original_price' => $prices['original_price'],
            'currency' => $this->currency($ctx),
            'rating' => null,
            'review_count' => null,
            'image_url' => $this->productImageUrl->forProduct($p, 'category_page_grid', $ctx->storeId)
                ?? $this->helperImageUrl->forProduct($p, 'category_page_grid', $ctx->storeId),
            'url' => $p->getProductUrl(),
            'category' => null,
            'labels' => [],
            'attributes' => $this->optionAttributes($summary['options']),
            'in_stock' => $inStock ?? $this->salability->isSalable($p, $ctx),
            'short_description' => $this->cleanText((string)$p->getData('short_description')),
            'options' => $p->getTypeId() === Configurable::TYPE_CODE ? $this->configurableOptions($p) : [],
            'option_values' => [],
            'variant_of' => null,
            'has_required_custom_options' => $summary['required'],
            'custom_options' => $summary['custom_options'],
        ];

        return Product::fromArray($data);
    }

    /**
     * @param MagentoProductInterface[] $products
     */
    public function preloadRequestPaths(array $products, int $storeId): void
    {
        $ids = [];
        foreach ($products as $product) {
            $ids[] = (int)$product->getId();
        }
        if ($ids === []) {
            return;
        }

        $rewrites = $this->urlFinder->findAllByData([
            UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
            UrlRewrite::ENTITY_ID => $ids,
            UrlRewrite::STORE_ID => $storeId,
            UrlRewrite::REDIRECT_TYPE => 0,
        ]);

        $paths = [];
        foreach ($rewrites as $rewrite) {
            $entityId = (int)$rewrite->getEntityId();
            if (!isset($paths[$entityId]) || $rewrite->getIsAutogenerated()) {
                $paths[$entityId] = $rewrite->getRequestPath();
            }
        }

        foreach ($products as $product) {
            $product->setRequestPath($paths[(int)$product->getId()] ?? false);
        }
    }

    private function optionAttributes(array $optionCounts): array
    {
        $attributes = [];
        foreach ($optionCounts as $title => $count) {
            $attributes[$title] = $count . ' values';
        }
        return $attributes;
    }

    private function prices(MagentoProductInterface $p): array
    {
        try {
            $priceInfo = $p->getPriceInfo();
            $final = (float)$priceInfo->getPrice(FinalPrice::PRICE_CODE)->getValue();
            $regular = (float)$priceInfo->getPrice(RegularPrice::PRICE_CODE)->getValue();
        } catch (\Throwable $exception) {
            return ['price' => 0.0, 'original_price' => null];
        }

        return [
            'price' => $final,
            'original_price' => ($regular - $final) >= 0.01 ? $regular : null,
        ];
    }

    private function currency(SessionContext $ctx): string
    {
        return $this->storeManager->getStore($ctx->storeId)->getCurrentCurrencyCode();
    }

    private function brand(MagentoProductInterface $p): ?string
    {
        try {
            $text = $p->getAttributeText('manufacturer');
        } catch (\Throwable $exception) {
            return null;
        }

        if (is_array($text)) {
            $text = reset($text);
        }

        if ($text === false || $text === null) {
            return null;
        }

        $value = trim((string)$text);
        return $value !== '' ? $value : null;
    }

    private function configurableOptions(MagentoProductInterface $p): array
    {
        $typeInstance = $p->getTypeInstance();
        if (!$typeInstance instanceof Configurable) {
            return [];
        }

        $result = [];
        foreach ($typeInstance->getConfigurableAttributesAsArray($p) as $attribute) {
            $label = (string)($attribute['label'] ?? '');
            if ($label === '') {
                continue;
            }
            $values = [];
            foreach ((array)($attribute['options'] ?? []) as $option) {
                $optionLabel = $option['label'] ?? null;
                if ($optionLabel !== null && (string)$optionLabel !== '') {
                    $values[] = (string)$optionLabel;
                }
            }
            $result[$label] = $values;
        }
        return $result;
    }

    private function cleanText(string $text): ?string
    {
        $stripped = strip_tags($text);
        $collapsed = preg_replace('/\s+/', ' ', $stripped) ?? '';
        $trimmed = trim($this->collapseDoubledQuotes($collapsed));
        return $trimmed !== '' ? $trimmed : null;
    }

    private function collapseDoubledQuotes(string $text): string
    {
        return str_replace(['""', "''"], ['"', "'"], $text);
    }
}
